BEGIN TRANSACTION;
DROP TABLE IF EXISTS "curses";
CREATE TABLE IF NOT EXISTS "curses" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"day"	TEXT NOT NULL,
	"start_time"	BLOB NOT NULL,
	"stop_time"	BLOB NOT NULL,
	"room"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
