BEGIN TRANSACTION;
DROP TABLE IF EXISTS "lessons";
CREATE TABLE IF NOT EXISTS "lessons" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"day"	TEXT NOT NULL,
	"start_time"	INTEGER NOT NULL,
	"stop_time"	INTEGER NOT NULL,
	"room"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
